name: Build PRs

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run export
